const mongoose = require("mongoose");

const carSchema = new mongoose.Schema({
  model: String,
  type: String,
  pricePerDay: Number,
  availability: {
    type: Boolean,
    default: true,
  },
  imageUrl: {
    type: String,
    default: "https://placehold.co/600x360?text=Car+Image", // Default car image (reliable placeholder)
  },
  // Augmented fields generated by AI generator (optional)
  fixedFields: {
    type: Object,
    default: {},
  },
  features: {
    type: [String],
    default: [],
  },
  description: {
    type: String,
    default: "",
  },
  areas: {
    type: [String],
    default: [],
  },
  images: {
    type: [Object],
    default: [],
  },
});

module.exports = mongoose.model("Car", carSchema);
